import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";

const inter = Roboto({ subsets: ["latin"], weight: ["100","300","400","500","700","900"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <div className={"flex xl:flex-row flex-col-reverse justify-between xl:gap-64 h-screen"}>
                {children}
                <Navbar/>
            </div>
            </body>
        </html>
  );
}
